# Generated by Django 2.1.7 on 2021-07-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20210614_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Product'),
        ),
    ]
