# Generated by Django 2.1.7 on 2021-07-09 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Action_Platform', '0002_profile'),
        ('seller', '0003_auto_20210703_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='Action_Platform.UserProfile'),
        ),
    ]
